### ISSUE TITLE
Internal Exception // Undefined index: scope_opener PreGetPostsSniff.php on line 314

### ISSUE THREAD

**Issue by metalandcoffee** [Automattic/VIP-Coding-Standards#499] opened 2020-07-20 17:53 UTC
## Bug Description

The first error that occurs when I lint my `functions.php` is the following:

`An error occurred during processing; checking has been aborted. The error message was: Undefined index: scope_opener in /.../WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php on line 314`

I'm not sure what is causing this. The linting seems to still continue and the file is error heavy. But I was curious if there was any insight into why this is happening. 🤷🏾‍♀️

## Error Code
Internal.Exception

## Environment

Use `php -v` and `composer show` to get versions.

| Question                | Answer
| ------------------------| -------
| PHP version             | 7.2.1 
| PHP_CodeSniffer version | 3.5.5
| VIPCS version           | 2.1.0

## Tested Against `master` branch?

- [ ] I have verified the issue still exists in the `master` branch of VIPCS.
- [ ] I have verified the issue still exists in the `develop` branch of VIPCS.

**Comment by rebeccahum** [comment] 2020-07-20 22:22
@metalandcoffee Hiya, would we be able to get your copy of `functions.php`? Also, what happens when you run it via `phpcs -l`?

**Comment by jrfnl** [comment] 2020-07-28 03:16
@metalandcoffee I believe I have a fix for this issue, though I'd still very much would like to see the original code which triggered the error.

In the mean time, it would be awesome if you could test the fix I've pulled in PR #565 and could let us know if that fixes it for you.

**Comment by metalandcoffee** [comment] 2020-07-28 13:38
Hi @rebeccahum & @jrfnl !!! I'm sorry for the delay. Here is the `functions.php`. It's really long so I just attached it as a zip file.
[functions.php.zip](https://github.com/Automattic/VIP-Coding-Standards/files/4988633/functions.php.zip)

I'm going to test the fix now!

**Comment by metalandcoffee** [comment] 2020-07-28 13:46
@jrfnl I'm not getting that error anymore! ✨

**Comment by jrfnl** [comment] 2020-07-28 14:28
@metalandcoffee Thanks for testing.

I've had a look at the code and the issue was caused by the inline control structure use, i.e. `if () return;` without curly braces.

As it is, the would now throw a false positive for your code "Main WP_Query is being modified without `$query->is_main_query()` check", while the code does actually have a main query check.

Let me see if I can add a quick fix for that too.

**Comment by jrfnl** [comment] 2020-07-28 14:39
@metalandcoffee I've updated PR #565 with an additional fix to handle inline control structures better.

**Closed** 2020-07-28 16:23 UTC
Labels: Status: Awaiting feedback, Status: Has PR
