### ISSUE TITLE
WPCS 3.0 removes WordPress.PHP.StrictComparisons

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#493] opened 2020-07-08 15:30 UTC
WPCS 3.0 [removes](https://github.com/WordPress/WordPress-Coding-Standards/pull/1919) the `WordPress.PHP.StrictComparisons` sniff.

Without any changes, this will cause errors, so we should pull in `Universal.Operators.StrictComparisons` as well, once we have PHPCSExtra as a dependency.

**Comment by jrfnl** [comment] 2023-08-26 02:24
Closing as duplicate of #603, which was fixed in #779

**Closed by jrfnl** 2023-08-26 02:24 UTC
Labels: Status: Duplicate, Require: WPCS 3.0+
