### ISSUE TITLE
Catch usage of `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by vaurdan** [Automattic/VIP-Coding-Standards#221] opened 2018-09-17 12:42 UTC
In React, HTML is escaped by default, but it is possible to output raw HTML using the `dangerouslySetInnerHTML` property and passing in an object with an `__html` key.

Does it makes sense to flag this?

**Comment by nickdaugherty** [comment] 2018-09-18 19:12
This looks like a dupe of https://github.com/Automattic/VIP-Coding-Standards/issues/145

**Closed** 2018-10-16 22:56 UTC
Labels: enhancement, question
